In [2]:
# A model is a description of a system, usually expressed as an equation of some kind. Let’s say we have some data – measurements of variables x and y. We think that in the future, we’ll have measurements of more x-like values, and we’d like to be able to predict those ys.
# It looks like you could draw a nice straight line through this cloud of points. That means that a linear model might be a good choice for this data. We’ve just done the first step in the model-fitting process: we’ve decided to use a line – a simple linear model.
# The process of picking the correct line for this model is called “fitting:
# https://diamondage.com/2017/06/03/what-does-it-mean-to-fit-a-model-anyway/

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
a = np.array([1, 2])
y = np.dot(X, a)
print(X)


[[1 1]
 [1 2]
 [2 2]
 [2 3]]


In [4]:
print(a)

[1 2]


In [5]:
print(y)

[3 5 6 8]


In [6]:
y = y + 3
y

array([ 6,  8,  9, 11])

In [7]:
reg = LinearRegression().fit(X, y)
reg.score(X, y)

1.0

In [8]:
 reg.coef_

array([1., 2.])

In [9]:
reg.intercept_

3.0000000000000018

In [10]:
reg.predict(np.array([[3, 5]]))

array([16.])

In [16]:
y1 = np.array([3, 5111, 6, 81])
reg = LinearRegression().fit(X, y1)
reg.score(X, y)

-1516364.7499999998